% MERGEOPENSIMSETS Merge two sets of items from OpenSim API. This function
% works with BodySet, JointSet, MarkerSet, etc. Used for merging models
% generated by STAPLE separately. Note if the base Set contains already
% elements on the Set to merge, those will be skipped.
%
% aBaseOsimSet = mergeOpenSimSets(aBaseOsimSet, anOsimSetToMerge)
%
% Inputs:
%   aBaseOsimSet - an OpenSim Set of items intended to serve as base Set.
%       Items will be added here.
%
%   anOsimSetToMerge - an OpenSim Set the items of which will be added to 
%       aBaseOsimSet. Items already present in aBaseOsimSet will be
%       skipped.
%
% Outputs:
%   aBaseOsimSet - the input OpenSim set updated with the elements 
%       from anOsimSetToMerge that are not duplicated.
%
%
% See also MERGEOPENSIMMODELS.
%
%-------------------------------------------------------------------------%
%  Author:   Luca Modenese 
%  Copyright 2020 Luca Modenese
%-------------------------------------------------------------------------%
function aBaseOsimSet = mergeOpenSimSets(aBaseOsimSet, anOsimSetToMerge)

for n_item = 0:anOsimSetToMerge.getSize()-1
    
    % get current item from OpenSim Set
    cur_item = anOsimSetToMerge.get(n_item);
    
    % get current item name as string
    cur_item_name = char(cur_item.getName());
    
    % if current item is already in base Set then skip
    if aBaseOsimSet.getIndex(cur_item_name)>=0
        disp(['   skip ', cur_item_name, ' (duplicate)'])
        continue
    else
        % if not in base model then add for merging
        aBaseOsimSet.cloneAndAppend(cur_item);
        disp(['   add ', cur_item_name])
    end
end

end