% ----------------------------------------------------------------------- %
%    Author:   Luca Modenese, October 2015                                %
%    email:    l.modenese@sheffield.ac.uk                                 %
% ----------------------------------------------------------------------- %

% TO DO: write description
% this function given a structure of bony landmarks plots them and adds a
% label if the switch is active.

function plotBL(Markers, label_switch)
    MarkerNames = fields(Markers);
    N_markers = size(MarkerNames);
    for n = 1:N_markers
        curr_marker_name = MarkerNames{n};
    plot3(gca, Markers.(curr_marker_name)(1),...
        Markers.(curr_marker_name)(2),...
        Markers.(curr_marker_name)(3),...
        'o', 'MarkerSize',13,'MarkerEdgeColor','k','MarkerFaceColor',[0.49, 0.49, 0.49],'Linewidth',3,'Color','r'); hold on
    if label_switch==1
    text(Markers.(curr_marker_name)(1),...
        Markers.(curr_marker_name)(2),...
        Markers.(curr_marker_name)(3),...
        curr_marker_name,...
        'VerticalAlignment', 'Baseline',...
        'BackgroundColor',[1 1 1],...
        'EdgeColor','black',...
        'FontSize',8);
    end
    end
    end